### PR TITLE
translate more properties

### PR DESCRIPTION
**Pull request by Boldewyn**
This should be almost the complete CSS 2.1 set + often used CSS 3
properties.

I could not test the thing myself, however, because gulp ended with an error:

```
ReferenceError: Promise is not defined
```

Therefore relying on TravisCI results.

### CODE REVIEW

**Comment by Boldewyn** [comment]
Hm. These are strange errors:

```
  1) postcss-german-stylesheets converts rahmen-bild-anfang to border-image-outset:

      AssertionError: expected 'a{ border-image-anfang: 10px; }' to deeply equal 'a{ border-image-outset: 10px; }'

      + expected - actual

      -a{ border-image-anfang: 10px; }

      +a{ border-image-outset: 10px; }



      at test/test.js:9:31
```

"border-image-anfang" what?

Edit: Ah, OK. I understand now. Will try to fix stuff.

**Comment by ntwcklng** [comment]
+1 should also fix my rearrangement for the colornames (simple ones to the bottom)

**Comment by Boldewyn** [comment]
@ntwcklng unfortunately not, because I changed only the property handling. That has a reason: Properties are always one single matching string (like `border-image`). Values may be combined. If I changed that, too, values like

```
hintergrund: grün url(foo.png) nicht-wiederholen;
```

would stop working.

(That could be addressed by doing the replacement with anchored regexps, `.replace(new RegExp('\\b'+value+'\\b'))`, but I haven't looked into all the consequences yet.)

**Comment by timche** [comment]
I will have a look at it, thanks!

**Comment by timche** [comment]
I will have a look at it, thanks!

**Pull request merged**
